# Основные настройки нативного транслятора .java кода
# Используется стиль ant -> dev/jnic/web/**; dev.jnic.web.Shit* (https://stackoverflow.com/a/22636142)
# ** - совпадение по внутренним путям и именам
# * - совпадение по следующим символам (ShitClass -> Shit*)
main:
  # Включает в компиляцию класс(-ы)
  includes:
    - "net/minecraft/client/main/**"
    - "net/minecraft/client/main/Main"
  # Исключает из компиляции класс(-ы)
  excludes:
    - ""
  # Включает использование аннотаций для включения/исключения
  # Полностью отключает два предыдущих параметра
  use-annotations: false
  # Включает подробную информацию о компиляции (дебаг)
  debug-enabled: true
