# Основные настройки нативного транслятора .java кода
# Используется стиль ant -> dev/jnic/web/**; dev.jnic.web.Shit* (https://stackoverflow.com/a/22636142)
# ** - совпадение по внутренним путям и именам
# * - совпадение по следующим символам (ShitClass -> Shit*)
# Пустые includes и excludes (нулевое значение пустое) дают понять, что включать надо ВСЕ классы
main:
  # Включает в компиляцию класс(-ы)
  includes:
    - "dev/**"
  # Исключает из компиляции класс(-ы)
  excludes:
    - "codes/**"
  # Включает использование аннотаций для включения/исключения
  # Полностью отключает два предыдущих параметра
  use-annotations: true
  # Очищать аннотации VMProtect
  clean-vmprotect-annotations: false
  # Включает подробную информацию о компиляции (дебаг)
  debug-enabled: false
# Настройки работы с референсами
reference:
  # Ссылка на сервер, в котором референсы частично декриптятся
  reference-url: "http://localhost:6555/decrypt"
  # Начальная константа сида
  seed-constant: 583485834
  # Фактор рандома
  random-factor: 6364136222846791005
  # Начальный ключ для ксора сида
  xor-constant: 56474
